{"abstract":[{"type":"text","text":"An error occured while encoding certificate data"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"certificateEncodingDataError"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/digimecore\/sdkerror\/certificateencodingdataerror"]}],"identifier":{"url":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SDKError\/certificateEncodingDataError","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore","doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SDKError"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"certificateEncodingDataError","kind":"identifier"}],"externalID":"s:10DigiMeCore8SDKErrorO28certificateEncodingDataErroryA2CmF","title":"SDKError.certificateEncodingDataError","role":"symbol","modules":[{"name":"DigiMeCore"}],"roleHeading":"Case","symbolKind":"case"},"references":{"doc://digimecore.DigiMeCore/documentation/DigiMeCore":{"role":"collection","title":"DigiMeCore","url":"\/documentation\/digimecore","abstract":[],"kind":"symbol","identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore","type":"topic"},"doc://digimecore.DigiMeCore/documentation/DigiMeCore/SDKError":{"identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SDKError","role":"symbol","title":"SDKError","url":"\/documentation\/digimecore\/sdkerror","kind":"symbol","navigatorTitle":[{"text":"SDKError","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDKError"}],"abstract":[{"type":"text","text":"SDK Errors"}],"type":"topic"},"doc://digimecore.DigiMeCore/documentation/DigiMeCore/SDKError/certificateEncodingDataError":{"role":"symbol","abstract":[{"type":"text","text":"An error occured while encoding certificate data"}],"identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SDKError\/certificateEncodingDataError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"certificateEncodingDataError"}],"url":"\/documentation\/digimecore\/sdkerror\/certificateencodingdataerror","title":"SDKError.certificateEncodingDataError","kind":"symbol","type":"topic"}}}