{"metadata":{"role":"symbol","modules":[{"name":"DigiMeCore"}],"title":"SDKError.urlRequestFailed(error:)","symbolKind":"case","externalID":"s:10DigiMeCore8SDKErrorO16urlRequestFailedyACs5Error_p_tcACmF","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"urlRequestFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Case"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"An error occurred when communicating with digi.me server. Contains underlying error - typically an instance of URLError","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SDKError\/urlRequestFailed(error:)"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlRequestFailed"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/digimecore\/sdkerror\/urlrequestfailed(error:)"]}],"hierarchy":{"paths":[["doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore","doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SDKError"]]},"kind":"symbol","references":{"doc://digimecore.DigiMeCore/documentation/DigiMeCore/SDKError":{"identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SDKError","role":"symbol","title":"SDKError","url":"\/documentation\/digimecore\/sdkerror","kind":"symbol","navigatorTitle":[{"text":"SDKError","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDKError"}],"abstract":[{"type":"text","text":"SDK Errors"}],"type":"topic"},"doc://digimecore.DigiMeCore/documentation/DigiMeCore":{"role":"collection","title":"DigiMeCore","url":"\/documentation\/digimecore","abstract":[],"kind":"symbol","identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore","type":"topic"},"doc://digimecore.DigiMeCore/documentation/DigiMeCore/SDKError/urlRequestFailed(error:)":{"kind":"symbol","title":"SDKError.urlRequestFailed(error:)","abstract":[{"type":"text","text":"An error occurred when communicating with digi.me server. Contains underlying error - typically an instance of URLError"}],"url":"\/documentation\/digimecore\/sdkerror\/urlrequestfailed(error:)","identifier":"doc:\/\/digimecore.DigiMeCore\/documentation\/DigiMeCore\/SDKError\/urlRequestFailed(error:)","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlRequestFailed"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}]}}}